import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            background: "none",
            padding: 0,
            margin: 0
          }}
        >
          <Image
            src="/logo.png"
            alt="mInvoice logo"
            width={220}
            height={60}
            style={{
              opacity: 0.85,
              filter: "drop-shadow(0 2px 8px rgba(0,0,0,0.08))",
              background: "none",
              padding: 0,
              margin: 0,
              marginBottom: "12px"
            }}
          />
        </div>
        {children}
        <footer
          style={{
            width: "100%",
            textAlign: "center",
            fontSize: "1rem",
            color: "#888",
            marginTop: "32px",
            marginBottom: "12px",
            letterSpacing: "0.01em"
          }}
        >
          Made with <span style={{color: "#e25555"}}>❤️</span> by Mehul Panchal
        </footer>
      </body>
    </html>
  );
}
